##
## EPITECH PROJECT, 2020
## CNA_trade-master
## File description:
## Makefile
##

all:
	@cp trade.py trade
	@chmod +x trade
	@printf "Ready !\n"

clean:
	@rm -rf ./src/__pycache__
	@rm -f trade
	@printf "Cleanned\n"

fclean: clean

re: fclean all
