##
## EPITECH PROJECT, 2021
## Makefile generated with Yumiko
## File description
## Makefile
##

NAME = zappy_ai

all:
	@chmod +x $(NAME)
	@printf "\033[32m[ DONE ]\033[0m\tAdded rights\n"
	@cp $(NAME) ../$(NAME)
	@printf "\033[32m[ DONE ]\033[0m\tCopied\n"

clean:
	@rm ../$(NAME)
	@printf "\033[32m[ DONE ]\033[0m\tCleanned $(NAME)\n"

fclean:	clean

re:	fclean all

.PHONY: all clean fclean re
