##
## EPITECH PROJECT, 2020
## pushswapTest
## File description:
## Makefile
##

SRC	=	pushswap_checker.hs

NAME	=	pushswap_checker

RM	=	rm -rf

all:	$(NAME)

$(NAME):
		ghc $(SRC) -o $(NAME)

clean:
	rm -f *.o *.hi

fclean: clean
	rm -f $(NAME)
	rm -f *.o *.hi

re: fclean all